### PR TITLE
Update/fix crash issues with Android-Iconics library for Android 10.0 devices

### LINKED ISSUE #99: [bug] Neko crashes on Android 10 devices
**Describe the bug**
Application crashes on devices that's on Android 10.0 (API 29). 

**To Reproduce**
1. Run on device that has API 29.
2. See "Neko keeps stopping" launch error.

**Expected behavior**
App should launch with no issue.

**Screenshots**
launch_error

**Please complete the following information:**
 - Device: [Pixel 3XL]
 - Android Version: [ Android 10]
 - Version [10.0]

**Additional context**
Here is the stack output [error](https://pastebin.com/pqUFg2Eu). If you look at the stack trace there seems to be an issue with the old version of Android-Iconics when it calls the getValue method of the ReflectionUtils object. 

I think this problem occurs because of the new Android 10.0 [update ](https://developer.android.com/about/versions/10/non-sdk-q#q-list-changes) restricting the use of reflection to get certain attributes. It seems like updating to the newer version of Android-Iconics will fix this problem. 

In my [fork](https://github.com/arsonistAnt/Neko/commit/94213a0036fab7989d2836f9e29d2948311b0f63) I was able to update iconics successfully & being able to launch the app. It required a bit of refactoring of some old methods that were used because of some lib changes.  I don't know if this is the correct way to go about this issue but if its okay I can make a pull request to apply these changes. 

_I think any use of reflection in this app should be closely considered due to restrictions placed on them in Android 10.0._

### PR DESCRIPTION
**Pull request by arsonistAnt**
Closes #99 .

Some refactoring has been done in order to upgrade to the new version of Android-Iconics so some method calls have been changed. 

Also, I removed the reflection usage in the `PageIndicatorTextView `which was used to create an outlining effect for the text. An alternative was to use a span object that creates the outline and set it in the `setText` method.

### CODE REVIEW

File: app/src/main/java/eu/kanade/tachiyomi/ui/reader/PageIndicatorTextView.kt [hunk 1]
```diff
@@ -42,20 +29,22 @@ class PageIndicatorTextView(
...
-        // We need to use reflection to set the text color instead of using [setTextColor],
-        // otherwise the view is invalidated inside [onDraw] and there's an infinite loop
-        val textColorField = TextView::class.java.getDeclaredField("mCurTextColor").apply {
-            isAccessible = true
-        }!!
+        // A span object with text outlining properties
+        val spanOutline = OutlineSpan(
+                strokeColor = Color.rgb(45, 45, 45),
+                strokeWidth = 4f
+        )
```
Comment (nonproto) [inline app/src/main/java/eu/kanade/tachiyomi/ui/reader/PageIndicatorTextView.kt:48]: does the infinite loop not happen anymore?

Comment (arsonistAnt) [reply app/src/main/java/eu/kanade/tachiyomi/ui/reader/PageIndicatorTextView.kt:48]: It doesn't, I tried setting a timber log in the onDraw method to check as well. Seems like setting the textColor in the onDraw has been resolved?
